### PR TITLE
Changed namespace and classnames to adhere to the PSR-1 recommendation.

### PR DESCRIPTION
**Pull request by sanderdekroon**
Recommendations are found on the php-fig website: http://www.php-fig.org/psr/. They make sure packages are somewhat uniform in usage. 

I only applied the PSR-1 recommendations as found here: http://www.php-fig.org/psr/psr-1/. Though I would like to know if you're open to refactor the class, so that the namespaced functions become part of the class as methods.

Also, Travis seems to fail since composer is not executing dump-autoload.

### CODE REVIEW

**Comment by 0x13a** [comment]
Hi thank you for the PR! In order to merge please update the example in the reader as well and make the build pass. Once done that I will merge it.

Thanks a lot,

Cheers

**Comment by sanderdekroon** [comment]
Well that's just odd. I've just committed the changes, but it seems Travis is still failing. But when I run PHPUnit locally all the tests pass. Any ideas on why Travis fails?

**Comment by 0x13a** [comment]
let me have a look

**Comment by furan917** [comment]
HHVM and 5.6 >  Class undefined: Geodistance\Location in /home/travis/build/0x13a/geodistance-php/tests/GeodistanceTest.php on line 15

7 > 1) GeodistanceTest\GeodistanceTest::testLocationShouldThrowExceptionOnInvalidCoordinates
Failed asserting that exception of type "Error" matches expected exception "\InvalidArgumentException".

**Comment by sanderdekroon** [comment]
Allright, the tests (finally) pass! 

Since I changed the classname to Location (note the uppercase L), composer was also looking for a file called 'Location.php' in /src/. Unfortunately, I forgot PSR-4 works that way 😅. 

The reason the tests passed on my machine, was because I'm running OSX and OSX is case-insensitive when it comes to filenames. So while Composer is looking for Location.php, OSX thinks location.php is the same. Travis is running on Linux which _is_ case-sensitive making the tests fail.

I hope everything's alright now! :)

**Comment by 0x13a** [comment]
great, sorry if I didn't check it out, but i actually have zero time. 
thanks a lot for your contribution, hope this will help other people as well.

**Pull request merged**
